language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: FK1WNdJHEVxn0qUYyb1HXIYdO3P433Nj//SroY4ejGOympu8Hqk5Rh/83QHZdLi2gHyBc2IaWtEvUBtzIdScsGVo8lrtHiUEf2UK5OOp8CLFA5Pg92Hk11gTKScSx0I0gCmAurdE+IZJsnqv0valAAoDsSHDNlQIvHlA4B/R6EjijVwKQSfdg8nGveua8IGWXbK56HAAMSt3eNk/Jku/bxw69VVNWbc8RojHIiYm0PHKzIIDcCc8fzrCK5s7/RJGa1BmwRbY4PMhshZbKNx7DGvNlmu6zNEF+/SI4U3dgxxoOVyVBn95Gs+qn0ZctFh5bmRsWzoN+LfOrOglxpVbul4NFjGXyexE/qPQGBmxHCWfKI+9zbOJO4vsAm62MmLp7gGOUYtC7Tu63b+jsweNe8mdP1Ob/0vy6Rfs21NU3Mu/x1WBQThJtVzUpRpCvB53/UsCI15eFXXoJQDywQuWt/StPrnAiWq4Shhm68QGBKiFhXIWXCjjwXuA9wdMw6TJoKBuhuivk+r06vMDuGJGASpRLL4EV0nRRiuEBkCmljBXbrxMuhQQPI+1qlSRZJSUo4/B21ZPvVDR/pfBp1FXvuz72dWeMqTzinLhrUoGujA5prqw+RCfO9UhL2Fs86Ny8/cSTm5AAbACYHfSvI/OqQU6g6XRolJO9jSwqm+s2Ms=
  on:
    tags: true
    repo: Shipkore/libshipkore
    python: 3.8
