language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: innerkore
  password:
    secure: RYoYFJmK0ahT8QGsMy+EpSv3AXc5eD1eg8QWiPEXO0rRrUgoymvQVPmZZn7gvULvrmsfaAzkf0dNlCq1TlX5Wg8ejRkEuZ7C7++KRqrSBmMvUrXqnIlpK40Y/VhLDBcYCzryjwY5ujVGUNpFOMqj+b6D2CAPmdczcEJDQXS6xfMnQph67dXekPzKrmrrGdSyU2c6mRiDxjrzjUqKM8g9gZ9fEq6y+DIHiE3KDWf3LwLhsYFvFwKR0UYr33R4dk9HhuRItaggvR2hz2AIi2loGkF1Pyt+msZmr/6jPzleEiZhLsVxFmjJI9sgGENZG6IybuNZAHjjJNp0/GWM1OUNxEwrlIPBB+xM7FHJgsHO07DYSE7d9oGlp33cfcx2/nJyz037QY1s7mQhqrGBVF8Qmk93syKTE2Ga07QO4BhN9bCVjG6f7ANAxGAhrfAuTwaDeKqdu1qKaj4SrNc/p6tTHyiQAoHSuMzwIuLsAhVw0p2IyoLufaGLT2hWNYJi2r4iQcXDXgg5LQtX3awg4PjIyp4V+SnvqYU49Hjl1eD5qJXIvXRPKKyxMtFBRaDE+7fJI1+EK3YOiY4Mp0rQXRg5FhX7fo4jx8HtzLNtZoIUeOk4P220ojwspehL2V79NiDBtsYqLp/r5ExzwAVTzo2oSbqqjEInhboyoz7cY1mueTg=
  on:
    tags: true
    repo: Shipkore/libshipkore
    python: 3.8
